# Generated by Django 3.0.3 on 2020-03-05 05:10

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_index', models.IntegerField(null=True, verbose_name='章节')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': '章节列表',
            },
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_classification', models.IntegerField(choices=[(0, '普通课程'), (1, '微课'), (2, 'Demo'), (3, '总量')], verbose_name='课程类型')),
            ],
            options={
                'verbose_name': '课程数据',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('sort_index', models.IntegerField(null=True, verbose_name='课时')),
                ('is_video', models.BooleanField(default=True, null=True, verbose_name='是否为视频')),
                ('video', models.CharField(blank=True, max_length=128, null=True, verbose_name='课程视频')),
                ('video_length', models.CharField(blank=True, max_length=16, null=True, verbose_name='视频长度')),
                ('content', models.TextField(blank=True, null=True, verbose_name='图文内容(markdown)')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='course.Chapter')),
            ],
            options={
                'verbose_name_plural': '课时列表',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('course', '课程'), ('micro', '微课'), ('demo', 'Demo')], default='course', max_length=12, verbose_name='课程类型')),
                ('user', models.IntegerField(verbose_name='上传用户ID')),
                ('title', models.CharField(max_length=128, null=True, verbose_name='标题')),
                ('brief', models.TextField(default='', verbose_name='课程简介')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='课程介绍')),
                ('thumbnail', models.CharField(blank=True, max_length=256, null=True, verbose_name='课程图')),
                ('is_video', models.BooleanField(default=True, null=True, verbose_name='视频课程')),
                ('video', models.CharField(blank=True, default='', max_length=128, verbose_name='视频地址')),
                ('video_length', models.CharField(blank=True, default='', max_length=16, verbose_name='视频长度')),
                ('content', models.TextField(blank=True, default='', verbose_name='图文内容(markdown)')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='原价')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='现价')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否上架')),
                ('sale_earnings', models.DecimalField(decimal_places=2, default=0.8, max_digits=10, null=True, verbose_name='分销收益')),
                ('share_earnings', models.DecimalField(decimal_places=2, default=0.05, max_digits=10, null=True, verbose_name='分享收益')),
                ('share_discount', models.DecimalField(decimal_places=2, default=0.6, max_digits=10, null=True, verbose_name='分享折扣')),
                ('promotion_expire', models.DateTimeField(blank=True, null=True, verbose_name='优惠到期时间')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='是否加入促销')),
                ('display_hot', models.IntegerField(default=300, null=True, verbose_name='显示热度')),
                ('real_hot', models.IntegerField(default=0, null=True, verbose_name='真实热度')),
                ('display_rank', models.DecimalField(decimal_places=2, default=4.0, max_digits=10, verbose_name='显示评分')),
                ('real_rank', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='真实评分')),
                ('study_count', models.IntegerField(default=0, verbose_name='学习人数')),
                ('favour_count', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论人数')),
                ('lecture_count', models.IntegerField(default=0, verbose_name='课时数')),
                ('tech', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='技术栈')),
                ('env', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='运行环境')),
                ('banner', models.CharField(blank=True, max_length=256, null=True, verbose_name='课程横幅')),
                ('video_status', models.BooleanField(default=False, verbose_name='转码完成')),
                ('upload_thumbnail', models.ImageField(blank=True, null=True, upload_to=course.models.UploadTo('thumbnail/'), verbose_name='上传课程图')),
                ('upload_banner', models.ImageField(blank=True, null=True, upload_to=course.models.UploadTo('banner/'), verbose_name='banner')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '课程列表',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.Course'),
        ),
    ]
