# Generated by Django 3.0.3 on 2020-03-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='用户密码')),
                ('mobile', models.CharField(blank=True, default='', max_length=11, verbose_name='用户手机号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='用户邮箱')),
                ('nick_name', models.CharField(blank=True, default='', max_length=32, verbose_name='昵称')),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='地区')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255, verbose_name='头像')),
                ('open_id', models.CharField(blank=True, default='', max_length=255, verbose_name='微信open_id')),
                ('union_id', models.CharField(blank=True, default='', max_length=255, verbose_name='微信union_id')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('brief', models.CharField(default='这个人很懒...', max_length=32, verbose_name='个人一句话简介')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
                ('level', models.IntegerField(choices=[(0, '官方账号'), (1, '普通用户')], default=1, verbose_name='账号等级')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'f_user',
            },
        ),
    ]
