# Generated by Django 3.0.3 on 2020-03-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用户密码'),
        ),
    ]
